version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=\"dev\""
stack_name = "delete"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9x3n3er9e23q"
s3_prefix = "delete"
confirm_changeset = true
disable_rollback = true
image_repositories = []
